### ISSUE TITLE
Build raspotify addon with custom-built librespot with metadata pipe feature

### ISSUE THREAD

**Issue by marecabo** [marecabo/hassio-addons-ulrar#2]
See [billsq's pr](https://github.com/librespot-org/librespot/pull/214)
https://github.com/marecabo/librespot

Need to merge the build scripts and dockerfiles of both librespot and raspotify.

**Comment by Ulrar** [comment]
Hey,

FYI I just pushed that to my repo, seems to be working fine but it'll be nice to have someone else give it a try to confirm.
The only thing is that building from the rust sources seems to use quite a bit of ram on my system, I hope it doesn't break the building for anyone on rpi, might be time to look into publishing pre-built images.

**Comment by marecabo** [comment]
Hey Ulrar, 

great thanks for picking this up and letting me know. About an hour ago, I triggered a build an my RPi4 with 2 GB (about 1 GB free) and will report on how long it took - and how it worked.

However, as the forked-daapd addon already takes about half an hour to build on my Pi, pre-built images would be pretty convenient, I'd have to admit.

**Comment by marecabo** [comment]
It did work, thanks a lot @Ulrar! 🎉 I see title, artist and album title in forked-daapd. Building actually just took about an hour, and it is also working on my aarch64 HA version.

![image](https://user-images.githubusercontent.com/23156476/87835621-f4217a00-c88d-11ea-9a9c-9a7bc1a1b0ff.png)

**Comment by marecabo** [comment]
fixed by https://github.com/Ulrar/hassio-addons/commit/eba94f0e01c139d41b27a75ff02ffede25a99f27

**Comment by Ulrar** [comment]
Hey,

That's great, thanks for confirming !
I'll look into pre built images when I get some time off.
